app_config/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')), # デバッグツール
    path('', views.index, name='index'),
    path('app_folder/', include('app_folder.urls')),
]

app_folder/urls.py
from django.urls import path
from . import views

app_name = 'app_folder'
urlpatterns = [
    path('', views.TopView.as_view(), name='top_page'),
    path('top_page/', views.TopView.as_view(), name='top_page'),
    
    # app1 CRUD処理アプリ　ポケポケDB
    path('app1_index/', views.App1View.as_view(), name='app1_index'),

    # app2 APIと非同期通信
    path('app2_top/', views.App2View.as_view(), name='app2_top'),

]

"""
#    path('app1_form/<int:id>', views.App1View.as_view(), name='app1_edit'),
#    path('app1_form/', views.App1View.as_view(), name='app1_create'),

"""

app_folder/forms.py
from django import forms
from app_folder.modules import common
# from django.core.exceptions import ValidationError
# from django.utils.translation import gettext_lazy as _
from .models import Card_summary


packnamedict = common.packNameDict  # パックコードとパック名の対照dict
card_categorydict = common.cardCategoryDict # カードカテゴリ番号とカテゴリ名の対照dict
card_classdict    = common.cardClassDict    # カードクラス番号とクラス名の対照dict
card_elementdict  = common.cardElementDict  # 属性番号と属性名の対照dict
card_elementdict['0'] = "---"

class CardRegisterForm(forms.Form):
    name          = forms.CharField(label='カード名', max_length=50, empty_value="", strip=True ) # 必須
    name_english  = forms.CharField(label='英語名', max_length=50, required=False, empty_value="", strip=True )
    pack_code     = forms.ChoiceField(label="パック名", widget=forms.widgets.Select, choices=(packnamedict), ) # 必須
    pack_card_id  = forms.IntegerField(label='パック内カードID', min_value=1, max_value=9999) # 必須
    card_category = forms.ChoiceField(label='カードカテゴリ', widget=forms.widgets.Select, choices=(card_categorydict), ) # 必須
    card_class    = forms.ChoiceField(label='カードクラス',   widget=forms.widgets.Select, choices=(card_classdict), ) # 必須
    element       = forms.ChoiceField(label="属性", widget=forms.widgets.Select, choices=(card_elementdict), required=False, ) # 必須
    ex            = forms.BooleanField(label="ex", widget=forms.widgets.CheckboxInput, required=False,)
    all_card_id  = forms.IntegerField(label='全体カードID', widget=forms.widgets.NumberInput, min_value=1, max_value=9999, ) # 必須

    category_pokemon  = common.category_pokemon
    category_trainers = common.category_trainers
    class_pokemon     = common.class_pokemon
    class_trainers    = common.class_trainers
    non_element = 0

    #--------------------------------
    # バリデーション(フィールド個別)
    #--------------------------------
    
    # card_class
    # クラス カテゴリがポケモン[1]の時はクラスでグッズ等[456]は選べない,
    # トレーナーズ[2]の時は逆にたねや進化[123]は選べない
    def clean_card_class(self):
        print("IN clean_card_class")
        card_category = int(self.cleaned_data["card_category"])
        card_class = int(self.cleaned_data["card_class"])

        if card_category == self.category_trainers:
            if card_class in self.class_pokemon:
                self.add_error('card_class', "カードカテゴリがトレーナーズの際、クラスは[サポート,グッズ,かせき]から選択してください")

        elif card_category == self.category_pokemon:
            if card_class in self.class_trainers:
                self.add_error('card_class', "カテゴリがトレーナーズの時、クラスは[たね,1進化,2進化]から選択してください")
        return card_class

    # element
    # カテゴリがトレーナーズ[2]の時はエレメントは選べない
    def clean_element(self):
        print("IN clean_element")
        card_category = int(self.cleaned_data["card_category"])
        element = int(self.cleaned_data["element"])

        if card_category == self.category_trainers:
            if element:
                self.add_error('element', "カードカテゴリがトレーナーズの際、属性は選択できません")

        elif card_category == self.category_pokemon:
            if element is self.non_element:
                self.add_error('element', "カードカテゴリがポケモンの際、属性は必須です")
        return element

    # ex
    # カテゴリがトレーナーズ[2]の時exは選択できない
    def clean_ex(self):
        print("IN clean_ex")
        card_category = int(self.cleaned_data["card_category"])
        ex = self.cleaned_data["ex"]

        if card_category == self.category_trainers:
            if ex:
                self.add_error('ex', "カードカテゴリがトレーナーズの際、exは選択できません")
        return ex

# 新規作成フォーム
class CardCreateForm(CardRegisterForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['all_card_id'].disabled = True
    
    # pack_card_id
    # パック名+パックIDがユニークにならない場合はエラー(DBに組み合わせ制約あり)
    def clean_pack_card_id(self):    
        print("IN clean_pack_card_id")
        pack_code = self.cleaned_data["pack_code"]
        pack_card_id = int(self.cleaned_data["pack_card_id"])

        result = Card_summary.objects.select_related("detail").order_by('all_card_id')
        result = result.filter(pack_code=pack_code)
        result = result.filter(pack_card_id=pack_card_id)

        if result:
            self.add_error('pack_card_id', "指定されたパック名+パックIDの組み合わせは既に登録されています")
        return pack_card_id
    
    #--------------------------------
    # バリデーション(all_card_idが不正に操作されていた場合でall_card_idが既に存在している場合)
    # クライアントからの値は表示のみで全て無信用のため、不要となった(都度IDのMAX値+1を取得する方針)
    #--------------------------------
    # def clean_all_card_id(self):
    #     print("IN clean all_card_id")
    #     all_card_id = int(self.cleaned_data["all_card_id"])

    #     result = Card_summary.objects.filter(all_card_id=all_card_id).exists()
        
    #     if result:
    #         self.add_error('all_card_id', "全体カードIDが不正です")
    #         # raise forms.ValidationError('全体カードIDが既に存在しています')
    #     return all_card_id

# アップデートフォーム
class CardUpdateForm(CardRegisterForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['all_card_id'].widget.attrs['readonly']  = 'readonly'
        self.fields['all_card_id'].widget.attrs['class']     = 'form-control'

    #--------------------------------
    # バリデーション(個別)
    #--------------------------------
    # all_card_idが不正に操作されていた場合
    # 存在しないレコードにアップデートをかけないために実施、
    def clean_all_card_id(self):
        print("IN clean all_card_id update")
        all_card_id = int(self.cleaned_data["all_card_id"])

        result = Card_summary.objects.filter(all_card_id=all_card_id).exists()

        if not result:
            self.add_error('all_card_id', "全体カードIDが不正です")
        return all_card_id
    
    # pack_card_id
    # 登録時、入力されたパック名+パックIDが重複した場合はエラー 
    # だが、重複したレコードのall_card_idが、編集しているformの同fieldのinitialと同じ場合 は問題ない
    def clean_pack_card_id(self):    
        print("IN clean_pack_card_id")
        pack_code = self.cleaned_data["pack_code"]
        pack_card_id = int(self.cleaned_data["pack_card_id"])

        result = Card_summary.objects.filter(pack_code=pack_code, pack_card_id=pack_card_id).exists()

        if result:
            result2 = Card_summary.objects.get(pack_code=pack_code, pack_card_id=pack_card_id)
            if result2.all_card_id != int(self['all_card_id'].initial):
                self.add_error('pack_card_id', "指定されたパック名+パックIDの組み合わせは既に登録されています")
        return pack_card_id

app_folder/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.db import transaction
from django.core.paginator import Paginator
from .models import Card_summary, Card_detail, Pokedex
from .forms import CardCreateForm, CardUpdateForm
from app_folder.modules import common
import pandas as pd, glob
import math

# top ポートフォリオにかかわる初期設定周りで、その他便利そうなツールはこの画面に追加していく
# 
# Top1View class内分岐
# get 
#   DB_init_pokedex top_page.htmlから[btn_DBInit_pokedex]ボタンで返ってきた際の処理 DBの初期登録を行う
#   DB_init_card    top_page.htmlから[btn_DBInit_card]   ボタンで返ってきた際の処理 DBの初期登録を行う
# 　fetchNameE　     top_page.htmlから[btn_fetchNameE]ボタンで返ってきた際の処理 英語名のないレコードにpokedex テーブルから英語名を登録
# 　DB_reset 　      top_page.htmlから[btn_tables_reset]ボタンで返ってきた際の処理 アプリ内に関するレコードを全削除し,initialを再度実行できるようにする

class TopView(View):
    category_pokemon = 1 # カードカテゴリ1はポケモン
    ok_msg = [
        "pokedexテーブルの初期登録が完了しました!",
        "カード情報の初期登録が完了しました!",
        "レコードをすべて削除しました(1~3の再登録が可能となりました)",
    ]
    ng_msg = [
        "テーブルの初期登録は必要ありません",
        "現在、取得できるポケモン英語名はありません",
    ]

    def get(self, request, *args, **kwargs):
        # DBinit_pokedex_GET
        if (request.GET.get('btn_DBInit_pokedex')):
            print("__checkIn__ topview get DBinit_pokedex IN")
            context = {}

            file_pokedex = glob.glob(common.filedir_pokedex)
            csv_data_pokedex = pd.read_csv(file_pokedex[0], index_col=None, header=0)

            # pokedexのレコード数とcsvのレコード数を比べ、csvの方が多いときに実行する-後で状態保存テーブルから状態をとってきて初回だけ登録できる仕様に変える
            csv_pokedex_num = len(csv_data_pokedex)
            db_pokedex_num = Pokedex.objects.all().count()

            # DB追加処理
            if (csv_pokedex_num > db_pokedex_num):
                print("__checkIn__ topview get DBinit_pokedex try-create")
                with transaction.atomic():
                    pokedex_items=[]
                    for row in csv_data_pokedex.itertuples():
                        tmp = Pokedex(
                            pokedex_id=row.pokedex_id,
                            name_j=row.name_j,
                            name_e=row.name_e,
                        )
                        pokedex_items.append(tmp)
                    Pokedex.objects.bulk_create(pokedex_items)
                    context['complete_text'] = self.ok_msg[0]
            else:
                print("__checkIn__ topview get DBinit_pokedex non-create")
                context['ng_text'] = self.ng_msg[0]


            return render(request, 'app_folder/top_page.html', context=context)
        
        # DBinit_card_GET
        elif (request.GET.get('btn_DBInit_card')):
            print("__checkIn__ topview get DBinit_card IN")            
            # csvをsummary,detailに登録する
            context = {}

            file_card_sumarry = glob.glob(common.filedir_card_summary)
            file_card_detail  = glob.glob(common.filedir_card_detail)

            csv_data_card_summary = pd.read_csv(file_card_sumarry[0], index_col=None, header=0)
            csv_data_card_detail  = pd.read_csv(file_card_detail[0], index_col=None, header=0)

            csv_card_summary_num = len(csv_data_card_summary)
            db_card_summary_num = Card_summary.objects.all().count()

            # DB追加処理
            if (csv_card_summary_num > db_card_summary_num):
                print("__checkIn__ topview get DBinit_card_summary/detail try-create")
                with transaction.atomic():
                    if len(csv_data_card_summary) == len(csv_data_card_detail):# sumarryとdetailで同じ数になることを担保
                        # card_summaryリスト作成
                        card_summary_items=[]
                        for row in csv_data_card_summary.itertuples():
                            card_summary = Card_summary(
                                all_card_id   = row.all_card_id,
                                pack_code     = row.pack_code,
                                pack_card_id  = row.pack_card_id,
                                name          = row.name,
                                name_english  = "",
                                card_category = row.card_category,
                                card_class    = row.card_class,
                                rarity        = 0,
                            )
                            card_summary_items.append(card_summary)

                        Card_summary.objects.bulk_create(card_summary_items)

                        # card_detailリスト作成
                        card_detail_items=[]
                        for row in csv_data_card_detail.itertuples():
                            card_summary = Card_summary.objects.get(all_card_id=row.all_card)
                            card_detail = Card_detail(
                                all_card=card_summary,
                                ex = row.ex
                            )
                            if math.isnan(row.element)==False:# elementが0でないことを確認
                                card_detail.element = row.element
                            card_detail_items.append(card_detail)

                        Card_detail.objects.bulk_create(card_detail_items)

                        context['complete_text'] = self.ok_msg[1]
                    print("card create complete")
                    # elif:

            else:
                print("__checkIn__ topview get DBinit_pokedex non-create")
                context['ng_text'] = self.ng_msg[0]

            return render(request, 'app_folder/top_page.html', context=context)

        # fetchNameE_GET
        elif (request.GET.get('btn_fetchNameE')):
            print("__checkIn__ topview get fetchNameE IN")
            context = {}

            nameELess_Rcds = Card_summary.objects.order_by('all_card_id')
            nameELess_Rcds = nameELess_Rcds.filter(card_category = self.category_pokemon) 
            nameELess_Rcds = nameELess_Rcds.filter(name_english = "")
            num_rcds = len(nameELess_Rcds)

            # DB[card_summary.name_english] 更新処理
            if num_rcds > 0:
                print("__checkIn__ topview get fetchNameE try-update")
                # DB更新処理
                with transaction.atomic():
                    nameE_updateCount = 0
                    for i in range(num_rcds):
                        search_name = nameELess_Rcds[i].name
                        if "ex" in search_name:
                            search_name = search_name.replace('ex','').strip()
                        if "パルデア" in search_name:
                            search_name = search_name.replace('パルデア','').strip()

                        # 1.mysqlでカラカラ、ガラガラが同一とみなされてしまうため、回避策
                        # 2.また第8世代以降の英語名データがcsvにないため、pokedexにもない。カードサマリから得た検索ワードにヒットするレコードがpokedexテーブルに1あることを担保している
                        filter_count = Pokedex.objects.filter(name_j=search_name).count()   
                        if filter_count == 1:
                            pokedex = Pokedex.objects.get(name_j=search_name)
                            nameELess_Rcds[i].name_english = pokedex.name_e

                            nameE_updateCount = nameE_updateCount+1

                    Card_summary.objects.bulk_update(nameELess_Rcds, fields=["name_english"])
                    if nameE_updateCount == 0:
                        context['complete_text'] = self.ng_msg[1]
                    else:
                        context['complete_text'] = str(nameE_updateCount)+"件のポケモン英語名が新規取得されました!"
            else:
                print("__checkIn__ topview get fetchNameE non-Update")
                context['ng_text'] = self.ng_msg[1]

            return render(request, 'app_folder/top_page.html',context=context)

        # DB_reset_GET
        elif (request.GET.get('btn_tables_reset')):
            print("__checkIn__ topview get btn_tables_reset ")
            context = {}

            # アプリ内に関係するレコードを全削除し,リセットする処理
            with transaction.atomic():
                Card_detail.objects.all().delete()
                Card_summary.objects.all().delete()
                Pokedex.objects.all().delete()

            context['complete_text'] = self.ok_msg[2]
            return render(request, 'app_folder/top_page.html',context=context)

        # top 初期表示時 
        else:
            return render(request, 'app_folder/top_page.html')


# app1 ポケポケDB(基本的なCRUD)
# 
# App1View class内分岐
# get create app1_index.htmlから新規登録リンクで返ってきた際の処理
#     edit   app1_index.htmlから編集リンクで返ってきた際の処理
#     search app1_index.htmlからbtn_searchで返ってきた際の処理
#     index  'app_folder/app1_index/'にgetプロパティ無しで入った場合の処理
#
# post create app1_form.htmlからbtn_createボタンで返ってきた際の処理
#      edit   app1_form.htmlからbtn_editボタンで返ってきた際の処理
#      delete modal_predelete.htmlからbtn_deleteで返ってきた際の処理

class App1View(View):

    template_app1_form  = 'app_folder/app1_form.html'
    template_app1_index = 'app_folder/app1_index.html'

    per_page_num      = common.per_page_num  # ページ内表示レコード数
    packnamedict      = common.packNameDict  # パックコードとパック名の対照dict
    card_categorydict = common.cardCategoryDict # カードカテゴリ番号とカテゴリ名の対照dict
    card_classdict    = common.cardClassDict    # カードクラス番号とクラス名の対照dict
    card_elementdict  = common.cardElementDict  # 属性番号と属性名の対照dict
    category_trainers = 2 # カードカテゴリ2はトレーナーズカード

    def get(self, request, *args, **kwargs):
        # Create_GET
        if (request.GET.get('create')):
            print("__checkIn__ app1view get CREATE IN")
            
            last_rcd = Card_summary.objects.order_by('all_card_id').last()
            create_id = last_rcd.all_card_id+1

            form = CardCreateForm(initial={"all_card_id":create_id})
            context = {
                'create_all_card_id':create_id,
                'form':form,
               }

            return render(request, self.template_app1_form, context=context)

        # Edit_GET
        elif (request.GET.get('edit')):
            print("__checkIn__ app1view get EDIT IN")
            edit_all_card_id = int(request.GET.get('edit'))

templates/app_folder/app1_form.html
{% extends 'base.html' %}
{% block contents %}
{% load static %}

<P>　</P><h4 class="mt-5 mb-4 border-bottom">ポケモンカードポケット カードDB</h4>

<div class="container-fluid">
    {% if edit_all_card_id %}
        <h5>カード情報 の修正</h5>
    {% elif create_all_card_id %} 
        <h5>カード情報 の新規登録</h5>
    {% endif %}

    <form action="{% url 'app_folder:app1_index' %}" method="post">{% csrf_token %}
        <table class="table-hover">
            {{ form.non_field_errors }}
            {# 全体カードID #}
            <div class="field">
                <tr>
                    <th>{{ form.all_card_id.label_tag }}</th>
                    <td>{{ form.all_card_id }}</td>
                    <td>{{ form.all_card_id.errors }}</td>
                </tr>
            </div>
            {# カード名 #}
            <div class="field">
                <tr>
                    <th>{{ form.name.label_tag }}</th>
                    <td >{{ form.name }}</td>
                    <td>{{ form.name.errors }}</td>
                </tr>
            </div>
            {# カード名_英語 #}
            <div class="field">
                <tr>
                    <th>{{ form.name_english.label_tag }}</th>
                    <td>{{ form.name_english }}</td>
                    <td>{{ form.name_english.errors }}</td>
                </tr>
            </div>
            {# パック名 #}
            <div class="field">
                <tr>
                    <th>{{ form.pack_code.label_tag }}</th>
                    <td>{{ form.pack_code }}</td>
                    <td>{{ form.pack_code.errors }}</td>
                </tr>
            </div>
            {# パック内カードNo #}
            <div class="field">
                <tr>
                    <th>{{ form.pack_card_id.label_tag }}</th>
                    <td>{{ form.pack_card_id }}</td>
                    <td>{{ form.pack_card_id.errors }}</td>
                </tr>
            </div>
            {# カードカテゴリ #}
            <div class="field">
                <tr>
                    <th>{{ form.card_category.label_tag }}</th>
                    <td>{{ form.card_category }}</td>
                    <td>{{ form.card_category.errors }}</td>
                </tr>
            </div>
            {# カードクラス #}
            <div class="field">
                <tr>
                    <th>{{ form.card_class.label_tag }}</th>
                    <td>{{ form.card_class }}</td>
                    <td>{{ form.card_class.errors }}</td>
                </tr>
            </div>
            {# 属性 #}
            <div class="field">
                <tr>
                    <th>{{ form.element.label_tag }}</th>
                    <td>{{ form.element }}</td>
                    <td>{{ form.element.errors }}</td>
                </tr>
            </div>
            {# ex #}
            <div class="field">
                <tr>
                    <th>{{ form.ex.label_tag }}</th>
                    <td>{{ form.ex }}</td>
                    <td>{{ form.ex.errors }}</td>
                </tr>
            </div>
        </table>

        {# 送信ボタン #}
        <div class="align-bottom field">
            {% if edit_all_card_id %}
                <button type="submit" id="btn_edit" name="btn_edit" value="btn_edit" class="btn btn-success col-1">送信</button>
            {% elif create_all_card_id %}
                <button type="submit" id="btn_create" name="btn_create" value="btn_create" class="btn btn-success col-2">送信</button>
            {% endif %}
        </div>
    </form>
  <a href="{% url 'app_folder:app1_index' %}">戻る</a>
</div>

{% endblock contents %}

{% block extra_js %}
<script>
$(function(){
    $(".errorlist li").css({
        'color': 'Red'  
    });
});

// 二重submit無効
$("form").on("submit", function onsubmit (event) {
    $(this).off("submit", onsubmit).on("submit", false);
    console.log("btn off")
});

</script>
{% endblock extra_js %}

templates/app_folder/top_page.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block contents %}
{% load static %}

{% comment %} <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head> {% endcomment %}

<div class="row mt-5"></div>
<h4 class="mt-5 mb-4 border-bottom">DB initial</h4>

<div class="container-fluid">
    {% csrf_token %}
    <form  action="{% url 'app_folder:top_page' %}" method="get">
    <h1>ST_portfolioの初期設定</h1>
    <div class="row col-12">
        {% if complete_text %}
            <div class="alert alert-warning col-12" role="alert">{{ complete_text }}</div>
        {% endif%}
        {% if ng_text %}
            <div class="alert alert-warning col-12" role="alert">{{ ng_text }}</div>
        {% endif%}

        <div class="card card-body col-md-12">
            <div class="form-group row">
                {# 1 #}
                <div class="col-6">
                    <div>専用ディレクトリ内に配置されたcsv(全国ずかん情報)からデータを読み込みます</div>
                    <button type="submit" id="btn_DBInit_pokedex" name="btn_DBInit_pokedex" value="btn_DBInit_pokedex">1.ずかんデータ反映</button>
                </div>   
                {# 2 #}
                <div class="col-6">
                    <div>専用ディレクトリ内に配置されたcsv(カード情報)からデータを読み込みます</div>
                    <button type="submit" id="btn_DBInit_card" name="btn_DBInit_card" value="btn_DBInit_card">2.カードデータ反映</button>
                </div>    
            </div>
            <div class="form-group row">
                {# 3 #}
                <div class="col-6">
                    <div>pokedexテーブルからcard_summaryテーブルに英名を読み込み,画像取得ができるようにします(※全国図鑑807以下のみ)</div>
                    <button type="submit" id="btn_fetchNameE" name="btn_fetchNameE" value="btn_fetchNameE">3.英語名を取得</button>
                    {% comment %} <p>最終適用日付：20XX:XX:XX</p> {% endcomment %}
                </div>      
            </div>
            <div class="form-group row">
                {# 9 #}
                <div class="col-6">
                    <div class="text-danger">※テーブルに登録されたレコードを削除し、1~3の機能を再度実行できるようにします</div>
                    <button type="submit" id="btn_tables_reset" name="btn_tables_reset" value="btn_tables_reset">アプリ内レコードを全削除</button>
                    {% comment %} <p>最終適用日付：20XX:XX:XX</p> {% endcomment %}
                </div>      
            </div>
        </div>
    </div>
    </form>
</div>

{% endblock contents %}

{% block extra_js %}
<script>
    // 二重submit無効
    $("form").on("submit", function onsubmit (event) {
        $(this).off("submit", onsubmit).on("submit", false);
        console.log("btn off")
    });

</script>
{% endblock extra_js %}